name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Aquí puedes especificar la rama en la que deseas que se realice el análisis

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11  # Puedes especificar la versión de Java que utilizas en tu proyecto

      - name: Build with Gradle
        run: ./gradlew build

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}